# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors

"""Python SDK for [OCX](https://github.com/ocx-sh/ocx).

`ocx-sdk` drives the ocx binary rather than reimplementing it: ocx owns
resolution, verification, and the identifier grammar, and this package gives
you typed, CWD-independent handles over the commands it exposes.

```python
from ocx_sdk import Ocx, bootstrap

ocx = Ocx(exe=bootstrap.ensure())
project = ocx.project("/srv/build")
project.pull()
project.exec(["task", "verify"])
```

**This module is the API.** Everything listed in `__all__` is the stable
surface; every other module is underscored and package-private, and the one
public submodule is `ocx_sdk.bootstrap`. Reaching into an underscored path
means the next release may move it without notice — pre-1.0, breaking
changes ship without shims.

Start at `Ocx` for the runtime API and `bootstrap.ensure` for provisioning.
"""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from . import bootstrap
from ._client import (
    UNSET,
    ConfigCommands,
    LazyMode,
    MaybeRetry,
    MaybeTimeout,
    Ocx,
    PackageCommands,
    PatchCommands,
    Project,
    Resolve,
)
from ._config import ConfigOverrides, OcxConfig
from ._envmodel import ComposedEnv
from ._errors import (
    AuthError,
    BootstrapError,
    ChecksumMismatchError,
    ConfigError,
    DataError,
    DirtyRcBlockError,
    DistManifestError,
    DownloadError,
    ExitCode,
    ForgeCapabilityUnavailableError,
    IoError,
    NotFoundError,
    OcxError,
    OcxExecutionError,
    OcxNotFoundError,
    OcxProcessError,
    OcxTimeoutError,
    PermissionDeniedError,
    PolicyBlockedError,
    ReferrersUnsupportedError,
    TempFailError,
    TransparencyLogUnavailableError,
    UnavailableError,
    UnsupportedKeyBackendError,
    UnsupportedPlatformError,
    UsageError,
    VersionCompatError,
)
from ._results import (
    AboutInfo,
    Advisory,
    AnnounceReport,
    Assertion,
    AttestationOutcome,
    AttestationReport,
    BlobSummary,
    BuildReceipt,
    Candidate,
    CapabilityCheck,
    CascadeCheckReport,
    CascadeRepairReport,
    CascadeReport,
    ClaimOwner,
    ClaimReport,
    CleanEntry,
    CommandResult,
    ConfigSetupReport,
    ConfigUpdateReport,
    CopiedPlatformRow,
    CopyReport,
    DepNode,
    DepsReport,
    DryRunEntry,
    EnvEntry,
    EnvEntryType,
    EnvReport,
    ErrorEnvelope,
    GroupStatus,
    IndexFinding,
    InfoResult,
    InspectedPackage,
    InspectReport,
    InstalledPackage,
    InstallReport,
    Integration,
    ListingSummary,
    LockStatus,
    LoginResult,
    LogoutResult,
    PackageBinding,
    PackageDescription,
    PullReport,
    PushResult,
    RefusedEntry,
    RemovalResult,
    RepairEntry,
    RepairOutcome,
    SbomEntry,
    SbomListingReport,
    SbomSummaryOut,
    SignatureEntry,
    SignatureLegReport,
    SignatureReport,
    SignedPlatformReport,
    SlotRow,
    StatusReport,
    SweepReport,
    SweptTagReport,
    TestResult,
    TestRun,
    ToolBinding,
    ToolRow,
    VerificationReport,
    VersionInfo,
    WhichResult,
    error_envelope,
    partial_report,
    tolerated_report,
)
from ._types import (
    MANAGED_CONFIG_DISABLED,
    MIN_SUPPORTED,
    TESTED_OCX_VERSION,
    Auth,
    BasicAuth,
    BearerAuth,
    Channel,
    ConstVar,
    EnvValue,
    HostEnv,
    InstallEnv,
    ListVar,
    LogLevel,
    PackageLike,
    PackageRef,
    PathVar,
    RetryPolicy,
    SignatureFormat,
)
from .bootstrap import DistSource, ensure


def _resolve_version() -> str:
    """Return the installed package version, or a fallback when running from source."""
    try:
        return _pkg_version("ocx-sdk")
    except PackageNotFoundError:
        return "0.0.0+unknown"


__version__ = _resolve_version()

__all__ = [
    "MANAGED_CONFIG_DISABLED",
    "MIN_SUPPORTED",
    "TESTED_OCX_VERSION",
    "UNSET",
    "AboutInfo",
    "Advisory",
    "AnnounceReport",
    "Assertion",
    "AttestationOutcome",
    "AttestationReport",
    "Auth",
    "AuthError",
    "BasicAuth",
    "BearerAuth",
    "BlobSummary",
    "BootstrapError",
    "BuildReceipt",
    "Candidate",
    "CapabilityCheck",
    "CascadeCheckReport",
    "CascadeRepairReport",
    "CascadeReport",
    "Channel",
    "ChecksumMismatchError",
    "ClaimOwner",
    "ClaimReport",
    "CleanEntry",
    "CommandResult",
    "ComposedEnv",
    "ConfigCommands",
    "ConfigError",
    "ConfigOverrides",
    "ConfigSetupReport",
    "ConfigUpdateReport",
    "ConstVar",
    "CopiedPlatformRow",
    "CopyReport",
    "DataError",
    "DepNode",
    "DepsReport",
    "DirtyRcBlockError",
    "DistManifestError",
    "DistSource",
    "DownloadError",
    "DryRunEntry",
    "EnvEntry",
    "EnvEntryType",
    "EnvReport",
    "EnvValue",
    "ErrorEnvelope",
    "ExitCode",
    "ForgeCapabilityUnavailableError",
    "GroupStatus",
    "HostEnv",
    "IndexFinding",
    "InfoResult",
    "InspectReport",
    "InspectedPackage",
    "InstallEnv",
    "InstallReport",
    "InstalledPackage",
    "Integration",
    "IoError",
    "LazyMode",
    "ListVar",
    "ListingSummary",
    "LockStatus",
    "LogLevel",
    "LoginResult",
    "LogoutResult",
    "MaybeRetry",
    "MaybeTimeout",
    "NotFoundError",
    "Ocx",
    "OcxConfig",
    "OcxError",
    "OcxExecutionError",
    "OcxNotFoundError",
    "OcxProcessError",
    "OcxTimeoutError",
    "PackageBinding",
    "PackageCommands",
    "PackageDescription",
    "PackageLike",
    "PackageRef",
    "PatchCommands",
    "PathVar",
    "PermissionDeniedError",
    "PolicyBlockedError",
    "Project",
    "PullReport",
    "PushResult",
    "ReferrersUnsupportedError",
    "RefusedEntry",
    "RemovalResult",
    "RepairEntry",
    "RepairOutcome",
    "Resolve",
    "RetryPolicy",
    "SbomEntry",
    "SbomListingReport",
    "SbomSummaryOut",
    "SignatureEntry",
    "SignatureFormat",
    "SignatureLegReport",
    "SignatureReport",
    "SignedPlatformReport",
    "SlotRow",
    "StatusReport",
    "SweepReport",
    "SweptTagReport",
    "TempFailError",
    "TestResult",
    "TestRun",
    "ToolBinding",
    "ToolRow",
    "TransparencyLogUnavailableError",
    "UnavailableError",
    "UnsupportedKeyBackendError",
    "UnsupportedPlatformError",
    "UsageError",
    "VerificationReport",
    "VersionCompatError",
    "VersionInfo",
    "WhichResult",
    "__version__",
    "bootstrap",
    "ensure",
    "error_envelope",
    "partial_report",
    "tolerated_report",
]
