"""Pin every parser against ocx's own published report contract.

`tests/fixtures/contract/reports.v1.json` is generated by ocx from the very
Rust types its CLI serializes (`cargo run -p ocx_schema -- reports`), so it is
evidence about the wire. The rest of this suite parses hand-written payloads,
which are evidence about whoever typed them — that is how three presence-rule
inversions reached `main` and one of them crashed `env()`.

Two failure classes are asserted, both of which end in a `KeyError` or a
silently empty struct at run time:

* **phantom** — the parser reads a key ocx never publishes, so it can only ever
  see `None` (or raise).
* **unsafe** — the parser `_need`s a key ocx may omit, so an ordinary run
  raises instead of returning a value.

A third, **lossy** — reading with `.get` a key ocx always writes — cannot break
a parse, so it is recorded in `_WAIVED` rather than fixed blind.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from test_results import _wire_reads

import ocx_sdk._results as _results

_CONTRACT = json.loads((Path(__file__).parents[1] / "fixtures/contract/reports.v1.json").read_text())
"""ocx's published `--format json` contract, vendored at a known version."""


_DEFS: dict[str, tuple[str, ...]] = {
    "AboutInfo": ("About",),
    "Advisory": ("LazyAdvisoryReport",),
    "Assertion": ("AssertionRecord",),
    "AttestationOutcome": ("AttestationOutcome",),
    "AttestationReport": ("AttestationReport",),
    "BlobSummary": ("BlobSummary",),
    "Candidate": ("CandidateOut",),
    # The SDK flattens ocx's one-key envelope, so it reads across both levels.
    "ConfigSetupReport": ("ConfigSetupData", "ManagedConfigEntry"),
    "ConfigUpdateReport": ("ConfigUpdateData",),
    "CopiedPlatformRow": ("CopiedPlatformRow",),
    "CopyReport": ("CopyReport",),
    "DepNode": ("Dependency",),
    "DepsReport": ("Dependencies",),
    "DryRunEntry": ("DryRunEntry",),
    "EnvEntry": ("EnvEntry",),
    "EnvReport": ("EnvVars",),
    "GroupStatus": ("GroupStatus",),
    "InspectReport": ("InspectReport",),
    "InspectedPackage": ("PackageInspect",),
    "InstalledPackage": ("InstallEntry",),
    "Integration": ("IntegrationAttribution",),
    "ListingSummary": ("ListingSummary",),
    "LockStatus": ("LockStatus",),
    "LoginResult": ("LoginResult",),
    "LogoutResult": ("LogoutResult",),
    "PackageBinding": ("BinaryAttribution",),
    # ocx's `PackageDescription` serializes as its inner block or `null`.
    "PackageDescription": ("Inner",),
    "PullReport": ("WarmedPaths",),
    "PushResult": ("PushReport",),
    "RefusedEntry": ("RefusedEntry",),
    "RemovalResult": ("RemovedEntry",),
    "SbomEntry": ("SbomEntry",),
    "SbomListingReport": ("SbomListingReport",),
    "SbomSummaryOut": ("SbomSummaryOut",),
    "SignatureEntry": ("SignatureEntry",),
    "SignatureLegReport": ("SignatureLegReport",),
    "SignatureReport": ("SignatureReport",),
    "SignedPlatformReport": ("SignedPlatformReport",),
    "StatusReport": ("StatusReport",),
    "SweepReport": ("SweepReport",),
    "SweptTagReport": ("SweptTagReport",),
    "TestResult": ("ScriptRunReport",),
    "TestRun": ("RunSummary",),
    "ToolBinding": ("ToolStatus",),
    "ToolRow": ("LockEntry",),
    "VerificationReport": ("VerificationReport",),
    "VersionInfo": ("VersionData",),
    "WhichResult": ("LocatedPath",),
}
"""Every parsing struct, against the contract definition(s) it reads.

A tuple rather than a name because two parsers read across a nesting level ocx
models as two types. `test_every_parsing_struct_is_mapped` is set-equality, so
a new parser with no row here fails rather than going unchecked.
"""


_WAIVED: dict[str, dict[str, set[str]]] = {
    "AboutInfo": {"lossy": {"build", "channel", "ci", "commit"}},
    "VersionInfo": {"lossy": {"build", "channel", "ci", "commit"}},
    "AttestationOutcome": {"unsafe": {"kind", "message", "predicate_type", "signed"}},
}
"""Disagreements this suite accepts, with the reason each one is not a defect.

`AboutInfo` / `VersionInfo` **lossy**: ocx declares these as plain `Option<T>`,
so they are always written and `null` on a dev build. D7 would read them with
`_need` and type them `| None`; they are read with `.get` instead, which
returns the same value for a `null` and additionally survives ocx dropping the
key. For a wrapper that tracks a moving CLI, tolerating the absence is worth
more than pinning the presence.

`AttestationOutcome` **unsafe**: the parser dispatches on `status` first and
only then reads the keys that variant carries. The contract models the
variants as a `oneOf`, and this suite intersects their required sets, so a key
required in one arm reads as optional overall. The dispatch is what makes the
`_need` safe, and it is covered by the per-variant tests in `test_results.py`.
"""


def _resolve(node: dict) -> tuple[set[str], set[str]]:
    """Return `(every key, keys present in every variant)` for one schema node.

    Follows `$ref`, and folds a `oneOf`/`anyOf` by unioning the keys and
    intersecting the required sets — a key is guaranteed only when every arm
    that is not `null` writes it.
    """
    if "$ref" in node:
        return _resolve(_CONTRACT["$defs"][node["$ref"].rsplit("/", 1)[-1]])
    branches = node.get("oneOf") or node.get("anyOf")
    if branches:
        arms = [_resolve(branch) for branch in branches if branch.get("type") != "null"]
        if not arms:
            return set(), set()
        return set().union(*(keys for keys, _ in arms)), set.intersection(*(required for _, required in arms))
    return set(node.get("properties", {})), set(node.get("required", []))


def _published(names: tuple[str, ...]) -> tuple[set[str], set[str]]:
    """Fold `_resolve` over every definition a parser reads across."""
    resolved = [_resolve(_CONTRACT["$defs"][name]) for name in names]
    return set().union(*(keys for keys, _ in resolved)), set().union(*(required for _, required in resolved))


def _waived(struct: str, kind: str) -> set[str]:
    """Keys this suite accepts for `struct` under `kind`."""
    return _WAIVED.get(struct, {}).get(kind, set())


def test_every_parsing_struct_is_mapped():
    """A parser with no contract row is a parser nothing pins."""
    from test_results import _parsing_structs

    assert set(_DEFS) == _parsing_structs()


@pytest.mark.parametrize(("struct", "names"), sorted(_DEFS.items()))
def test_no_parser_reads_a_key_ocx_never_publishes(struct: str, names: tuple[str, ...]):
    """A phantom key is a field that can only ever be `None`, or a raise."""
    published, _ = _published(names)
    reads = set().union(*_wire_reads(getattr(_results, struct)))
    assert reads - published - _waived(struct, "phantom") == set()


@pytest.mark.parametrize(("struct", "names"), sorted(_DEFS.items()))
def test_no_parser_demands_a_key_ocx_may_omit(struct: str, names: tuple[str, ...]):
    """`_need` on an omitted key raises on an ordinary run — the crash class."""
    _, required = _published(names)
    needed, _ = _wire_reads(getattr(_results, struct))
    assert needed - required - _waived(struct, "unsafe") == set()


@pytest.mark.parametrize(("struct", "names"), sorted(_DEFS.items()))
def test_optional_reads_are_of_keys_ocx_may_actually_omit(struct: str, names: tuple[str, ...]):
    """`.get` on an always-written key is safe but under-typed; see `_WAIVED`."""
    _, required = _published(names)
    _, optional = _wire_reads(getattr(_results, struct))
    assert optional & required - _waived(struct, "lossy") == set()


def test_every_waiver_names_a_real_disagreement():
    """A waiver that no longer applies hides the next real one."""
    stale = []
    for struct, kinds in _WAIVED.items():
        published, required = _published(_DEFS[struct])
        needed, optional = _wire_reads(getattr(_results, struct))
        actual = {
            "phantom": (needed | optional) - published,
            "unsafe": needed - required,
            "lossy": optional & required,
        }
        stale += [
            f"{struct}.{kind}: {sorted(keys - actual[kind])}" for kind, keys in kinds.items() if keys - actual[kind]
        ]
    assert stale == []
